version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22

  pre_build:
    commands:
      - echo Installing frontend dependencies...
      - cd frontend
      - npm install

  build:
    commands:
      - echo Building React frontend...
      - npm run build
      - cd ..

  post_build:
    commands:
      - echo Build completed successfully

artifacts:
  files:
    - '**/*'